version: '3.9'

services:
  twitee-api:
    image: registry.gamosaurus.fr/twitee-api:latest
    container_name: twitee-api
    ports:
      - 5057:5057
    environment:
      SRVPORT: $SRVPORT
      DBHOST: $DBHOST
      DBNAME: $DBNAME
      DBUSER: $DBUSER
      DBPASSWD: $DBPASSWD
      TOKEN_KEY: $TOKEN_KEY

  twitee-frontend:
    image: registry.gamosaurus.fr/twitee-frontend:latest
    container_name: twitee-frontend
    ports:
      - 80:80

  twitee-doc:
    image: registry.gamosaurus.fr/twitee-doc:latest
    container_name: twitee-doc
    ports:
      - 8082:80