version: '3.9'

services:
  twitee-api:
    image: https://registry.gamosaurus.fr:5000/twitee-api:latest
    container_name: twitee-api
    ports:
      - 5057:5057
    environment:
      SRVPORT: $SRVPORT
      DBHOST: $DBHOST
      DBNAME: $DBNAME
      DBUSER: $DBUSER
      DBPASSWD: $DBPASSWD
      TOKEN_KEY: $TOKEN_KEY

  twitee-doc:
    image: ulthane/project:twitee-docs-latest
    container_name: twitee-doc
    ports:
      - 8082:80