name: dockerize_twitee_backend

on:
  push:
    branches:
      - "RELEASE/backend"

jobs:
  build:
    name: Build Docker Image API
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_TAG: twitee-api-0.3.2
    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Docker Build Backend
        run: cd backend && docker build . --file Dockerfile --tag $DOCKER_USER/project:$DOCKER_TAG --tag $DOCKER_USER/project:twitee-api-latest --no-cache

      - name: Docker push version
        run: docker push ${{secrets.DOCKER_USERNAME}}/project:$DOCKER_TAG

      - name: Docker push latest
        run: docker push ${{secrets.DOCKER_USERNAME}}/project:twitee-api-latest