name: dockerize_twitee_backend

on:
  push:
    branches:
      - "RELEASE/backend"

jobs:
  build:
    name: Build Docker Image API
    runs-on: self-hosted
    env:
      # DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
      # DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_REGISTRY: localhost
      DOCKER_REGISTRY_PORT: 5000
      DOCKER_TAG: twitee-api-0.5.0
    steps:
      - uses: actions/checkout@v3

      #- name: Docker Login
      #  run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Docker Build Backend
        run: cd backend && docker build . --file Dockerfile --tag $DOCKER_REGISTRY:$DOCKER_REGISTRY_PORT/twitee-api:$DOCKER_TAG --tag $DOCKER_REGISTRY:$DOCKER_REGISTRY_PORT/twitee-api:latest --no-cache

      - name: Docker push version
        run: docker push $DOCKER_REGISTRY:$DOCKER_REGISTRY_PORT/twitee-api:$DOCKER_TAG

      - name: Docker push latest
        run: docker push $DOCKER_REGISTRY:$DOCKER_REGISTRY_PORT/twitee-api:latest