name: dockerize_twitee_backend

on:
  push:
    branches:
      - "RELEASE/backend"

jobs:
  build:
    name: Build Docker Image API
    runs-on: self-hosted
    env:
      DOCKER_REGISTRY: localhost
      DOCKER_REGISTRY_PORT: 5000
      DOCKER_PROJECT: twitee-api
      DOCKER_TAG: 0.5.0
    steps:
      - uses: actions/checkout@v3

      - name: Docker Build Backend
        run: cd backend && docker build . --file Dockerfile --tag $DOCKER_REGISTRY:$DOCKER_REGISTRY_PORT/$DOCKER_PROJECT:$DOCKER_TAG --tag $DOCKER_REGISTRY:$DOCKER_REGISTRY_PORT/$DOCKER_PROJECT:latest --no-cache

      - name: Docker push version
        run: docker push $DOCKER_REGISTRY:$DOCKER_REGISTRY_PORT/$DOCKER_PROJECT:$DOCKER_TAG

      - name: Docker push latest
        run: docker push $DOCKER_REGISTRY:$DOCKER_REGISTRY_PORT/$DOCKER_PROJECT:latest