name: dockerize_twitee_docs

on:
  push:
    branches:
      - "RELEASE/docs"

jobs:
  build:
    name: Build Docker Image DOCS
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_TAG: twitee-docs-0.4.0
    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      
      - name: Docker Build Docs
        run: cd docs && docker build . --file Dockerfile --tag ulthane/project:$DOCKER_TAG --tag ulthane/project:twitee-docs-latest --no-cache

      - name: Docker push version
        run: docker push ${{secrets.DOCKER_USERNAME}}/project:$DOCKER_TAG

      - name: Docker push latest
        run: docker push ${{secrets.DOCKER_USERNAME}}/project:twitee-docs-latest