name: dockerize_twitee_frontend

on:
  push:
    branches:
      - "RELEASE/frontend"

jobs:
  build:
    name: Build Docker Image Frontend
    runs-on: self-hosted
    env:
      DOCKER_REGISTRY: localhost
      DOCKER_REGISTRY_PORT: 5000
      DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_PROJECT: twitee-api
      DOCKER_TAG: 1.0.0
    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        run: docker login $DOCKER_REGISTRY:$DOCKER_REGISTRY_PORT -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Docker Build Frontend
        run: cd TWITEE-SPHERE && docker build . --file Dockerfile --tag $DOCKER_REGISTRY:$DOCKER_REGISTRY_PORT/twitee-frontend:$DOCKER_TAG --tag $DOCKER_REGISTRY:$DOCKER_REGISTRY_PORT/twitee-frontend:latest --no-cache

      - name: Docker push version
        run: docker push $DOCKER_REGISTRY:$DOCKER_REGISTRY_PORT/twitee-frontend:$DOCKER_TAG

      - name: Docker push latest
        run: docker push $DOCKER_REGISTRY:$DOCKER_REGISTRY_PORT/twitee-frontend:latest