name: dockerize_twitee_backend

on:
  push:
    branches:
      - "development"

jobs:
  build:
    name: Build Docker Image API
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_TAG: twitee-api-0.3.2
    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Docker Build
        run: cd backend && docker build . --file Dockerfile --tag ulthane/project:$DOCKER_TAG --no-cache

      - name: Docker push
        run: docker push ${{secrets.DOCKER_USERNAME}}/project:$DOCKER_TAG